# GitHub Actions workflow for Rust project
# Builds and tests the SC_Starter application on Windows
name: Rust

on:
  push:
    branches: ["master"]
    # Ignore documentation and configuration changes
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "*.md"
      - "**.txt"
      - "LICENSE"
  pull_request:
    branches: ["master"]
    # Ignore documentation and configuration changes
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "**/*.md"
      - "README.md"
      - "LICENSE"
  workflow_dispatch:

env:
  # Enable colored output for cargo commands
  CARGO_TERM_COLOR: always

jobs:
  build:
    # Use the latest available Windows runner
    runs-on: windows-latest
    steps:
      # Checkout the repository source code
      - uses: actions/checkout@v4

      # Install and configure Rust toolchain
      - name: Install
        shell: pwsh
        run: |
          wget https://static.rust-lang.org/dist/rust-1.90.0-i686-pc-windows-gnu.msi -OutFile rust.msi
          Start-Process ./rust.msi -ArgumentList '/quiet' -Wait
          Remove-Item ./rust.msi

      # Build the project in release mode
      - name: Build
        run: cargo b -r --target i686-pc-windows-gnu

      # Upload the built executable as an artifact
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Preview
          path: ./target/i686-pc-windows-gnu/release/sys_info.exe
